# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k1rFaHa83rgB39wAE_5f3_ePFs4NLFwO
"""

#pip install plotly
#pip install plotly pandas

#pip install streamlit

import streamlit as st

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Create a Streamlit app title
st.title('Diabestes Hospital Visualization')

# Load the dataset
data = pd.read_csv('Diabestes_Hospital_Encounters (1).csv')

# Visualization 1: Bar Chart with Filters
st.header("Visualization 1: Bar Chart with Filters")

# Filter options
selected_gender = st.selectbox("Select Gender:", ['All'] + data['gender'].unique().tolist(), index=0)
selected_age_group = st.selectbox("Select Age Group:", ['All'] + data['age_group'].unique().tolist(), index=0)

# Apply filters
filtered_data = data.copy()
if selected_gender != 'All':
    filtered_data = filtered_data[filtered_data['gender'] == selected_gender]
if selected_age_group != 'All':
    filtered_data = filtered_data[filtered_data['age_group'] == selected_age_group]

# Create bar chart
fig = px.bar(filtered_data, x='race', title='Patient Count by Race', labels={'race': 'Race', 'count': 'Patient Count'})
st.plotly_chart(fig, use_container_width=True)

data['HospitalStayLength'] = pd.to_numeric(data['HospitalStayLength'], errors='coerce')  # Convert to numeric

# Visualization 2: Pie Chart with Slider
st.header("Visualization 2: Pie Chart with Slider")

# Slider for the number of medications
num_meds_slider = st.slider("Select Number of Medications:", min_value=1, max_value=data['num_medications'].max(), value=5)

# Filter based on the number of medications
medication_data = data[data['num_medications'] == num_meds_slider]

# Create pie chart
fig = px.pie(medication_data, names='Diabetes_Med', title=f'Distribution of Diabetes Medication (Num Meds = {num_meds_slider})')
st.plotly_chart(fig, use_container_width=True)